# Generated by Django 4.1.7 on 2023-02-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reciepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('amount', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('name_student', models.CharField(max_length=100)),
                ('name_Payer', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=120)),
                ('amount_in_words', models.CharField(blank=True, max_length=120, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
